apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check
spec:
  schedule: "* * * * *" # runs the job every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: health-check
              image: myimage:latest
              command:
                - sh
                - -c
                - >
                  if [ -f /etc/dataone/health-status ]; then
                    kubectl patch configmap {{ .Release.Name }}-configfiles
                      --type merge -p '{"data":{"health-status":"healthy"}}'
                  else
                    kubectl patch configmap {{ .Release.Name }}-configfiles
                      --type merge -p '{"data":{"health-status":"unhealthy"}}'
                  fi
          restartPolicy: OnFailure
