apiVersion: v2
name: dataone-indexer
description: |
  Helm chart for Kubernetes Deployment of the dataone-indexer 
  (https://github.com/DataONEorg/dataone-indexer)

# OCI Annotations - see https://github.com/helm/helm/pull/11204
sources:
  - https://github.com/dataoneorg/dataone-indexer

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "1.2.0-develop"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "3.1.2-SNAPSHOT"

# Chart dependencies
dependencies:
  - name: rabbitmq
    condition: rabbitmq.enabled, global.rabbitmq.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 11.16.2    # rabbitmq version 3.11.18
    ## get full list using:  $  helm search repo bitnami/rabbitmq --versions
    ##
    ## NOTE: For upgrades beyond 10.3.9, see "Required feature flags in RabbitMQ 3.11.0":
    ## https://www.rabbitmq.com/blog/2022/07/20/required-feature-flags-in-rabbitmq-3.11
    ##
    ## We now have a postStart hook to run 'rabbitmqctl enable_feature_flag all' - so upgrades
    ## should be simpler (see .Values.rabbitmq.lifecycleHooks.postStart).
    ## However, note we must upgrade to the latest patch release of each minor (APP) version,
    ## before upgrading to the next minor (APP) version; see:
    ## https://www.rabbitmq.com/docs/feature-flags#version-compatibility
    ## ...so these should be the next upgrades, in order:
    ##  CHART VERSION          APP VERSION
    # version: 11.16.2   # rabbitmq version 3.11.18
    # version: 13.0.3    # rabbitmq version 3.12.13
    # version: 14.7.0    # rabbitmq version 3.13.7
    # ...then to latest app 4.0.x
    #
  - name: solr
    condition: solr.enabled, global.solr.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 9.5.5      # solr version 9.8.1 is deployed by chart version 9.5.5
    # get full list using:  $  helm search repo bitnami/solr --versions
